id: kubecost
displayName: Kubecost
description: |
  Kubecost provides real-time cost visibility for teams using Kubernetes, helping you continuously reduce your cloud costs. This quickstart allows users to ingest Kubecost metrics and build visualizations in New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://github.com/munwarm/kubecost-newrelic
keywords:
  - kubecost
  - opencost
  - kubernetes
  - cloud cost
categoryTerms:
  - containers
  - kubernetes
  - open source monitoring