# Sets the URL name of the quickstart on public I/O (required)
slug: kubecost

# Displayed in the UI (required)
title: Kubecost

# Long-form description of the quickstart (required)
description: |
  ## Quickstart for Kubecost Cost Monitoring
  Kubecost provides real-time cost visibility and insights for teams using Kubernetes, helping you continuously reduce your cloud costs.
  The link to New Relic blog provides instructions on how to send kubernetes cost metrics and build visualizations inside New Relic.
  The Kubecost quickstart includes:
  ## a dashboard
    where users can easily monitor cluster utilization and cost breakdown:
    - Total Cost by CPU, Memory, Storage and Network
    - Cost Breakdown by Node, Persistent Volume, Container, Storage and Network
    - CPU, RAM and Storage Utilization
    - CPU and RAM Requests

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  This quickstart allows users to ingest Kubecost metrics and build visualizations in New Relic.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Munwar Mohammed

# Keywords for filtering / searching criteria in the UI
keywords:
  keywords:
  - kubecost
  - opencost
  - kubernetes
  - cloud cost
  - containers

# Reference to dashboards to be included in this quickstart
dashboards:
  - kubecost

dataSourceIds:
  - kubecost

# Documentation references
documentation:
  - name: Set up Kubecost to send data to New Relic
    url: https://nerdlife.datanerd.us/new-relic/kubernetes-cost-monitoring
    description: Information on how to setup the Kubecost integration to send cost metrics to New Relic
  - name: Learn how to monitor and reduce Kubernetes cluster spend using Kubecost
    url: https://www.kubecost.com/
    description: Information on how Kubecost can be leveraged for real-time cost visibility and insights for teams using Kubernetes

# Content / Design
icon: logo.png
website: https://www.kubecost.com/